

# ################ USER ROUTES ################
# POST http://localhost:3000/api/schools
# Content-Type: application/json

# {
#   "SchoolDBN": "15K423",
#   "SchoolName": "Brooklyn Technical High School",
#   "StreetAddress": "29 Fort Greene Place",
#   "ZipCode": 11217,
#   "Neighborhood": "Fort Greene",
#   "District": 15,
#   "Borough": "Brooklyn",
#   "SchoolType": "General Education",
#   "GradeLevel": "High",
#   "CommunitySchool": true,
#   "CommunityBasedOrg": "Brooklyn Community Services",
#   "PartnershipYearStart": 2018,
#   "DataForSchoolYear": 2024,
#   "Enrollment": 5872,
#   "FemaleStudents": 0.45,
#   "MaleStudents": 0.55,
#   "SpecialNeedStudents": 0.12,
#   "ELLStudents": 0.08,
#   "LivingInPoverty": 0.42,
#   "EconomicNeed": 0.38,
#   "AsianStudents": 0.35,
#   "BlackStudents": 0.25,
#   "LatinoStudents": 0.15,
#   "MultiRaceStudents": 0.08,
#   "NativeAmericanStudents": 0.01,
#   "WhiteStudents": 0.15,
#   "OtherStudents": 0.01,
#   "Attendance2018Rate": 0.92,
#   "Attendance2019Rate": 0.93,
#   "Attendance2020Rate": 0.85,
#   "Attendance2021Rate": 0.88,
#   "Attendance2022Rate": 0.91,
#   "Attendance2023Rate": 0.94,
#   "Attendance2024Rate": 0.95,
#   "Chronically2018Absent": 0.18,
#   "Chronically2019Absent": 0.15,
#   "Chronically2020Absent": 0.28,
#   "Chronically2021Absent": 0.22,
#   "Chronically2022Absent": 0.16,
#   "Chronically2023Absent": 0.12,
#   "Chronically2024Absent": 0.10,
#   "Avg2018ELAScore": 612.5,
#   "Avg2019ELAScore": 615.2,
#   "Avg2020ELAScore": null,
#   "Avg2021ELAScore": 598.3,
#   "Avg2022ELAScore": 608.7,
#   "Avg2023ELAScore": 615.4,
#   "Avg2024ELAScore": 618.2,
#   "Proficient2018ELA": 0.68,
#   "Proficient2019ELA": 0.72,
#   "Proficient2020ELA": null,
#   "Proficient2021ELA": 0.65,
#   "Proficient2022ELA": 0.70,
#   "Proficient2023ELA": 0.73,
#   "Proficient2024ELA": 0.75,
#   "Avg2018MathScore": 625.8,
#   "Avg2019MathScore": 628.4,
#   "Avg2020MathScore": null,
#   "Avg2021MathScore": 618.2,
#   "Avg2022MathScore": 622.5,
#   "Avg2023MathScore": 627.8,
#   "Avg2024MathScore": 630.5,
#   "Proficient2018Math": 0.75,
#   "Proficient2019Math": 0.78,
#   "Proficient2020Math": null,
#   "Proficient2021Math": 0.72,
#   "Proficient2022Math": 0.76,
#   "Proficient2023Math": 0.79,
#   "Proficient2024Math": 0.81,
#   "SchoolLatitude": 40.6887,
#   "SchoolLongitude": -73.9765
# }

## Get All Schools:
# GET http://localhost:3000/api/public/schools/15K423

## Get Single School:
# GET /http://localhost:3000/api/public/schools/01M015

# PUT http://localhost:3000/api/public/schools/15K423
# Content-Type: application/json

# {
#   "Enrollment": 550,
#   "FemaleStudents": 52,
#   "MaleStudents": 48
# }

DELETE http://localhost:3000/api/schools/15K423
Content-Type: application/json



# GET USER BY ID
# Get User Maxine Shaw
# GET http://localhost:3000/api/users/6818523ea14e85e2dff7676a

# ADD NEW USERS
# POST http://localhost:3000/api/users
# Content-Type: application/json

# [
#   {
#     "user": "Maxine Shaw",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Athletic"
#   },
#   {
#     "user": "Kyle Barker",
#     "age": 30,
#     "height": 68,
#     "weight": 150,
#     "fitness": "Athletic"
#   },
#   {
#     "user": "Regine Hunter",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Beginner"
#   },
#   {
#     "user": "Overton Wakefield",
#     "age": 30,
#     "height": 68,
#     "weight": 150,
#     "fitness": "Intermediate"
#   },
#   {
#     "user": "Khadijah James",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Intermediate"
#   },
#   {
#     "user": "Synclair James",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Beginner"
#   }
# ]

# UPDATE USER BY ID
# Updating User Synclair James

# PUT http://localhost:3000/api/users/6818523ea14e85e2dff7676f
# Content-Type: application/json

# {
#   "user": "Synclaire James-Jones",
#   "age": 29
# }

# DELETE USER BY ID
# Delete User Maxine Shaw

# DELETE http://localhost:3000/api/users/6818523ea14e85e2dff7676a
# Content-Type: application/json


################ AEROBIC ROUTES ################

# GET ALL AEROBIC EXERCISES

# GET http://localhost:3000/api/aerobics

# GET AEROBIC EXERCISE BY ID 
#BBench Press

# GET http://localhost:3000/api/aerobics/681859d5a14e85e2dff76782


# ADD NEW AEROBIC EXERCISES

# POST http://localhost:3000/api/aerobics
# Content-Type: application/json

# [
#   {
#     "cardio": "Running",
#     "time": 30,
#     "intensity": 7,
#     "distance": 3.5
#   },
#   {
#     "cardio": "Swimming",
#     "time": 45,
#     "intensity": 6,
#     "distance": 2
#   },
#   {
#     "cardio": "Zumba",
#     "time": 42,
#     "intensity": 5,
#     "distance": 0
#   },
#   {
#     "cardio": "Treadmill",
#     "time": 30,
#     "intensity": 7,
#     "distance": 2
#   },
#   {
#     "cardio": "Hiking",
#     "time": 90,
#     "intensity": 6,
#     "distance": 4
#   }
# ]

# UPDATE AEROBIC EXERCISE BY ID
# Update Hiking

# PUT http://localhost:3000/api/aerobics/:id
# Content-Type: application/json

# {
#   "time": 95,
#   "intensity": 7
# }

# DELETE AEROBIC EXERCISE BY ID
# Delete Bench Press

# DELETE http://localhost:3000/api/aerobics/681859d5a14e85e2dff76782


############## WEIGHTLIFT ROUTES ################

# GET ALL WEIGHTLIFT EXERCISES

# GET http://localhost:3000/api/weightlifts

# GET WEIGHTLIFT EXERCISE BY ID
# Get Lunge:

# GET http://localhost:3000/api/weightlifts/681859d5a14e85e2dff76785


#ADD NEW WEIGHTLIFT EXERCISE

# POST http://localhost:3000/api/weightlifts
# Content-Type: application/json

# [
#   {
#     "exercise": "Bench Press",
#     "muscle": "Chest",
#     "weight": 135,
#     "reps": 10
#   },
#   {
#     "exercise": "Squat",
#     "muscle": "Legs",
#     "weight": 185,
#     "reps": 8
#   },
#   {
#     "exercise": "Leg Press",
#     "muscle": "Legs",
#     "weight": 90,
#     "reps": 4
#   },
#   {
#     "exercise": "Lunge",
#     "muscle": "Legs",
#     "weight": 120,
#     "reps": 6
#   },
#   {
#     "exercise": "Butterfly Press",
#     "muscle": "Arms",
#     "weight": 40,
#     "reps": 8
#   }
# ]

# UPDATE WEIGHTLIFT EXERCISE BY ID
# Update Butterly Press

# PUT http://localhost:3000/api/weightlifts/681859d5a14e85e2dff76786
# Content-Type: application/json
#
# {
#   "muscle": "Chest",
#   "reps": 10
# }

# DELETE WEIGHTLIFT EXERCISE BY ID
# Delete Lunge

# DELETE http://localhost:3000/api/weightlifts/681859d5a14e85e2dff76785