
# GET ALL PRODUCTS
# GET http://localhost:3000/api/products


# GET PRODUCT BY ID
# GET http://localhost:3000/api/products/6817048d2bbf21f133357882

# ADD NEW PRODUCTS
POST http://localhost:3000/api/products
Content-Type: application/json

[
  {
    "name": "Newish Product",
    "quantity": 2,
    "price": 8.99
  },
  {
    "name": "Gently-Loved Product",
    "quantity": 8,
    "price": 12.99
  }
]


# UPDATE PRODUCT BY ID
# PUT  http://localhost:3000/api/products/681704a82bbf21f133357884
#  Content-Type: application/json

# {
# "name" : "Newer Product",
# "price" : 10.99
# }

# DELETE PRODUCT BY ID
# DELETE http://localhost:3000/api/products/6817295ba460dac588392613
# Content-Type: application/json
