
################ USER ROUTES ################
#############################################

# GET ALL USERS 
# GET http://localhost:3000/api/users

# GET USER BY ID
# Get User Maxine Shaw
# GET http://localhost:3000/api/users/6818523ea14e85e2dff7676a

# ADD NEW USERS
# POST http://localhost:3000/api/users
# Content-Type: application/json
# [
#   {
#     "user": "Maxine Shaw",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Athletic"
#   },
#   {
#     "user": "Kyle Barker",
#     "age": 30,
#     "height": 68,
#     "weight": 150,
#     "fitness": "Athletic"
#   },
#   {
#     "user": "Regine Hunter",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Beginner"
#   },
#   {
#     "user": "Overton Wakefield",
#     "age": 30,
#     "height": 68,
#     "weight": 150,
#     "fitness": "Intermediate"
#   },
#   {
#     "user": "Khadijah James",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Intermediate"
#   },
#   {
#     "user": "Synclair James",
#     "age": 30,
#     "height": 65,
#     "weight": 150,
#     "fitness": "Beginner"
#   }
# ]

# UPDATE USER BY ID
# Updating User Synclair James
# PUT http://localhost:3000/api/users/6818523ea14e85e2dff7676f
# Content-Type: application/json
# {
#   "user": "Synclaire James-Jones",
#   "age": 29
# }

# DELETE USER BY ID
# Delete User Maxine Shaw
# DELETE http://localhost:3000/api/users/6818523ea14e85e2dff7676a
# Content-Type: application/json


################ AEROBIC ROUTES ################
################################################

# GET ALL AEROBIC EXERCISES
# GET http://localhost:3000/api/aerobics

# GET AEROBIC EXERCISE BY ID 
#BBench Press
# GET http://localhost:3000/api/aerobics/681859d5a14e85e2dff76782

# GET ALL AEROBIC EXERCISE BY USER ID
# GET http://localhost:3000//api/aerobics/user/:userId

# ADD NEW AEROBIC EXERCISES
# POST http://localhost:3000/api/aerobics
# Content-Type: application/json
# [
#   {
#     "cardio": "Running",
#     "time": 30,
#     "intensity": 7,
#     "distance": 3.5
#   },
#   {
#     "cardio": "Swimming",
#     "time": 45,
#     "intensity": 6,
#     "distance": 2
#   },
#   {
#     "cardio": "Zumba",
#     "time": 42,
#     "intensity": 5,
#     "distance": 0
#   },
#   {
#     "cardio": "Treadmill",
#     "time": 30,
#     "intensity": 7,
#     "distance": 2
#   },
#   {
#     "cardio": "Hiking",
#     "time": 90,
#     "intensity": 6,
#     "distance": 4
#   }
# ]

# UPDATE AEROBIC EXERCISE BY ID
# Update Hiking
# PUT http://localhost:3000/api/aerobics/:id
# Content-Type: application/json

# {
#   "time": 95,
#   "intensity": 7
# }

# DELETE AEROBIC EXERCISE BY ID
# Delete Bench Press
# DELETE http://localhost:3000/api/aerobics/681859d5a14e85e2dff76782


############## WEIGHTLIFT ROUTES ################
#################################################

# GET ALL WEIGHTLIFT EXERCISES
# GET http://localhost:3000/api/weightlifts

# GET ALL WEIGHTLIFT EXERCISE BY USER ID
# GET http://localhost:3000//api/weightlifts/user/:userId
 
# GET WEIGHTLIFT EXERCISE BY ID
# Get Lunge:

# GET http://localhost:3000/api/weightlifts/681859d5a14e85e2dff76785


#ADD NEW WEIGHTLIFT EXERCISE
# POST http://localhost:3000/api/weightlifts
# Content-Type: application/json
# [
#   {
#     "exercise": "Bench Press",
#     "muscle": "Chest",
#     "weight": 135,
#     "reps": 10
#   },
#   {
#     "exercise": "Squat",
#     "muscle": "Legs",
#     "weight": 185,
#     "reps": 8
#   },
#   {
#     "exercise": "Leg Press",
#     "muscle": "Legs",
#     "weight": 90,
#     "reps": 4
#   },
#   {
#     "exercise": "Lunge",
#     "muscle": "Legs",
#     "weight": 120,
#     "reps": 6
#   },
#   {
#     "exercise": "Butterfly Press",
#     "muscle": "Arms",
#     "weight": 40,
#     "reps": 8
#   }
# ]

# UPDATE WEIGHTLIFT EXERCISE BY ID
# Update Butterly Press
# PUT http://localhost:3000/api/weightlifts/681859d5a14e85e2dff76786
# Content-Type: application/json
#
# {
#   "muscle": "Chest",
#   "reps": 10
# }

# DELETE WEIGHTLIFT EXERCISE BY ID
# Delete Lunge
# DELETE http://localhost:3000/api/weightlifts/681859d5a14e85e2dff76785