POST http://localhost:3000/api/books
Content-Type: application/json

[
  {
    "title": "Running",
    "author": "Ronald McDonald",
    "publisher": 7
  },
  {
    "title": "Jogging",
    "author": "Burger King",
    "publisher": 7
  }
]
